title: "Zoeken, vinden en beoordelen van onderzoeksdata"
description: "Een eenvoudige website over het zoeken, vinden en beoordelen van onderzoeksdata."
theme: minima

# Custom title for the browser tab
title_separator: "|"
