title: "Zoeken, vinden en beoordelen van onderzoeksdata"
description: "Een eenvoudige website over het zoeken, vinden en beoordelen van onderzoeksdata."
theme: minima

# Add custom title for the header
title_separator: "|"

